### ISSUE TITLE
9.4 Release Notes missing Change to History.EventType Property

### ISSUE THREAD

**Issue by Dr34mR** [content-manager-sdk/Community#10]
9.3 SDK History.EventType property was the HistoryTypes enum. (9.3.0.178)
9.4 SDK History.EventType property is now the Events enum. (9.4.0.341)

Enum property names are not a 1 to 1 map
i.e. 
HistoryTypes.ErecAttachLocationType
Events.DocAttached

**Comment by Dr34mR** [comment]
Please let me know if you would like a Pull request in the future. Figured since the SDK site is generated by Doxygen that the source was outside of Github.

Haven't checked if the enum integers themselves are a 1to1 map yep.

**Comment by dchurchland** [comment]
Thanks Scotty, I added a note to the release notes.

Comment is simpler than pull request thanks.

**Comment by Dr34mR** [comment]
Cheers David. Much appreciated.
