### ISSUE TITLE
Should DatabaseConnectionPool be used?

### ISSUE THREAD

**Issue by catmanjan** [content-manager-sdk/Community#13]
This link seems to imply that database connection pooling is handled internally by calling Database connect: https://content-manager-sdk.github.io/Community/94/release_notes.html#rn_92_DatabasePool

However there is a new section on database pooling here: https://content-manager-sdk.github.io/Community/94/programming_guide.html#database_pooling

Is this just for added flexibility around cache settings, or should developers always be using the database pool in multiuser scenarios?

**Comment by catmanjan** [comment]
Also, what should be considered when setting ```MaxConnectionAge``` and ```MaxConnectionCount```?

What would be the side effect of setting these to ```int.MaxValue```?

**Comment by dchurchland** [comment]
In 92 the pooling was automatic, in 94 we added DatabaseConnectionPool to support configuration and monitoring.

I suppose it would be possible for it to be auto enabled but I suspect most applications will not require it and unless there is a compelling case for change I prefer not to change it again.

I have never investigated the memory footprint of the Database connection so I don't know whether setting MaxConnectionCount to int.MaxValue is likely to cause memory issues.  For myself I would just set it to a number that is comfortably larger than your maximum expected concurrent users.

In theory a database connection should be able to stay alive forever but I feel more comfortable if I know they are getting recycled periodically.  You could try setting MaxConnectionAge  to 8 hours or more and see if you have any issues.

**Comment by catmanjan** [comment]
Thanks @dchurchland, you say in 92 the pooling was automatic, does that mean it is no longer automatic?

**Comment by dchurchland** [comment]
Yes.  You have to instantiate the pool.

**Comment by catmanjan** [comment]
Thanks!
