### ISSUE TITLE
Sort record type searches by favorite?

### ISSUE THREAD

**Issue by catmanjan** [content-manager-sdk/Community#37]
I want to search for all record types sorting by the user's favorites

I tried the steps here https://hprm.info/Record-Type-Sort-Order/

But it only seems to apply to the favorite search, how can I sort a record type search for all record types, showing most recently favorited at the top, followed by other sort orders for unfavorited records?

**Comment by catmanjan** [comment]
On second look it seems the favorite search isnt being sorted either

**Comment by dchurchland** [comment]
I updated the post, does that help?

**Comment by catmanjan** [comment]
Great thanks, is there a way to set the "SelectRecordTypeUserOptionsFavoritesFirst" for just this one search and not modify the users default options?

**Comment by dchurchland** [comment]
Sorry, I do not understand.  Setting the user options is the way you set a
Record Type as a favourite.

**Comment by dchurchland** [comment]
Sure, just choose the appropriate value from RecordTypeFilter, for
example: RecordTypeFilter.All

**Comment by catmanjan** [comment]
RecordTypeFilter.All doesn't seem to do return record types favorites first, only RecordTypeFilter.AllForCreate

![image](https://user-images.githubusercontent.com/137350/211440044-abc79082-c6bb-4028-84ae-dca51d725442.png)

**Comment by dchurchland** [comment]
If that is the case then you will need to submit an enhancement request.
The feature to sort the Record Types in this way was created to allow the
UI to show the most interesting Record Types first when a user is creating
a Record so I am not surprised if it only the creation related filters.

**Comment by catmanjan** [comment]
Okay thanks I've logged a ticket
