### ISSUE TITLE
When ProcessEvent gets called.

### ISSUE THREAD

**Issue by abhis2007** [content-manager-sdk/Community#39]
referring https://github.com/content-manager-sdk/Community/blob/master/Samples/SDK/CSharp/EventProcessor/EventProcessor.cs

in this an inbuilt method is used "ProcessEvent" when it is getting triggered?

**Comment by dchurchland** [comment]
This is a sample for a Custom Event processor in Content Manager.  When you
configure the processor to run on a particular database in Content Manager
Enterprise Studio you can set it to run for all events or you can select
which object types and events you wish it to run for.

**Comment by abhis2007** [comment]
Got the understanding.
