### ISSUE TITLE
Multipart request to create a Record with an attachment AND access controls

### ISSUE THREAD

**Issue by catmanjan** [content-manager-sdk/Community#41]
Hello sorry I am weary of talking to support about this - 

A client is using multipart requests to create Records with attachments, this is working perfectly for all types of fields, Title, Container, additional fields, etc.

The problem is that they also want to set access controls (restrict View Metadata/View Document to certain users) at the time of creation.

We can't seem to get the multipart request to accept any format of the Access Controls property, we've tried JSON, form data but the Record is created unrestricted.

Can you offer any advice on how to create a Record with an attachment and access controls in a single request, or do we really need to do 2 requests as suggested by support?

**Comment by dchurchland** [comment]
Sorry Jan, you will have to make two requests.  I suggest upload the file
first then create the Record.  The multi-part upload uses a 'simplified'
form of JSON which is not great for representing complex objects so we long
ago made the choice to not support this.

**Comment by catmanjan** [comment]
Thanks, okay we'll have to look at a workaround...
